# Write your code here
print("Earned amount")
print("Bubblegum: $202")
print("Toffee: $118")
print("Ice cream: $2250")
print("Milk chocolate: $1680")
print("Doughnut: $1075")
print("Pancake: $80")
print("Income: $5405")
print("Staff expenses:")
staff_expenses = int(input())
print("Other expenses:")
other_expenses = int(input())
net_income = 5405 - (staff_expenses + other_expenses)
print('Net income: $' + str(net_income))
